In [1]:
#Ordinal / Label Encoding

In [2]:
import pandas as pd

In [4]:
df = pd.read_csv('customer.csv')
df.shape

(50, 5)

In [5]:
df.sample(5)

,age,gender,review,education,purchased
44,77,Female,Average,UG,No
26,53,Female,Poor,PG,No
1,68,Female,Poor,UG,No
29,83,Female,Average,UG,Yes
19,97,Male,Poor,PG,Yes


In [6]:
df = df.iloc[:,2:]

In [7]:
df.head()

,review,education,purchased
0,Average,School,No
1,Poor,UG,No
2,Good,PG,No
3,Good,PG,No
4,Average,UG,No


In [8]:
from sklearn.model_selection import train_test_split

In [9]:
x_train , x_test , y_train , y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

In [13]:
x_train

,review,education
5,Average,School
33,Good,PG
1,Poor,UG
24,Average,PG
3,Good,PG
22,Poor,PG
18,Good,School
4,Average,UG
37,Average,PG
17,Poor,UG


In [14]:
from sklearn.preprocessing import OrdinalEncoder

In [21]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])
oe.fit(x_train)


,categories,"[['Poor', 'Average', ...], ['School', 'UG', ...]]"
,dtype,<class 'numpy.float64'>
,handle_unknown,'error'
,unknown_value,None
,encoded_missing_value,nan
,min_frequency,None
,max_categories,None


In [20]:
x_train_encoded = oe.transform(x_train)
x_test_encoded = oe.transform(x_test)

In [22]:
x_train_encoded

array([[1., 0.],
       [2., 2.],
       [0., 1.],
       [1., 2.],
       [2., 2.],
       [0., 2.],
       [2., 0.],
       [1., 1.],
       [1., 2.],
       [0., 1.],
       [2., 1.],
       [0., 0.],
       [0., 2.],
       [0., 2.],
       [2., 1.],
       [2., 1.],
       [2., 0.],
       [2., 0.],
       [0., 2.],
       [1., 1.],
       [0., 1.],
       [2., 0.],
       [0., 2.],
       [0., 0.],
       [2., 1.],
       [0., 0.],
       [1., 0.],
       [1., 1.],
       [0., 2.],
       [2., 1.],
       [1., 0.],
       [2., 2.],
       [1., 1.],
       [2., 1.],
       [2., 2.],
       [2., 0.],
       [2., 2.],
       [0., 0.],
       [2., 2.],
       [1., 2.]])

In [23]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [24]:
from sklearn.preprocessing import LabelEncoder

In [26]:
lb = LabelEncoder()
lb.fit(y_train)

LabelEncoder()

In [28]:
lb.classes_

array(['No', 'Yes'], dtype=object)

In [27]:
y_train_encoded =lb.transform(y_train)
y_test_encoded = lb.transform(y_test)

In [30]:
y_train.head()

5     Yes
33    Yes
1      No
24    Yes
3      No
Name: purchased, dtype: object

In [31]:
y_train_encoded

array([1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0])

In [32]:
y_test_encoded

array([0, 1, 0, 1, 1, 1, 0, 0, 1, 0])