In [1]:
import pickle
import numpy as np

In [2]:
ohe_sex = pickle.load(open('models/ohe_sex.pkl','rb'))
ohe_emark = pickle.load(open('models/ohe_emark.pkl','rb'))
clf = pickle.load(open('models/clf.pkl','rb'))

In [3]:
test_input = np.array([2,'male',25,0,1,13,'S'],dtype=object).reshape(1,7)

In [4]:
test_input

array([[2, 'male', 25, 0, 1, 13, 'S']], dtype=object)

In [5]:
test_input_sex =ohe_sex.transform(test_input[:,1].reshape(1,1))

c:\Users\zhass\miniconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [6]:
test_input_sex.shape

(1, 2)

In [7]:
test_input_embark = ohe_emark.transform(test_input[:,-1].reshape(1,1))

c:\Users\zhass\miniconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [8]:
test_input_embark

array([[0., 0., 1., 0.]])

In [9]:
test_input_age = test_input[:,2].reshape(1,1)

In [11]:
test_input_age.shape

(1, 1)

In [12]:
test_input

array([[2, 'male', 25, 0, 1, 13, 'S']], dtype=object)

In [13]:
test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]],test_input_sex,test_input_age,test_input_embark),axis=1)

In [14]:
test_input_transformed.shape

(1, 11)

In [15]:
clf.n_features_in_

11

In [17]:
pred = clf.predict(test_input_transformed)