In [1]:
import pandas as pd

data = pd.read_csv('https://raw.githubusercontent.com/npradaschnor/Pima-Indians-Diabetes-Dataset/master/diabetes.csv')

data.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1


In [2]:
data.shape

(768, 9)

In [3]:
data.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [4]:
X = data.drop('Outcome', axis=1)
y = data['Outcome']

In [5]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2)


In [6]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,1000
,multi_class,'deprecated'


In [10]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [11]:
y_pred = model.predict(X_test)


In [13]:
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_test))

0.7662337662337663
[[109   0]
 [  0  45]]


In [15]:
y_scores = model.predict_proba(X_test)[:,1]
y_scores

array([0.04953686, 0.17458294, 0.09362175, 0.25508365, 0.63548857,
       0.11671443, 0.06567042, 0.4218973 , 0.04866081, 0.57563916,
       0.33874637, 0.413039  , 0.69854191, 0.19964447, 0.02001692,
       0.82470318, 0.86657228, 0.03101042, 0.2551059 , 0.89492626,
       0.95246057, 0.83478519, 0.11740746, 0.44671105, 0.08923267,
       0.06882492, 0.65117837, 0.41198118, 0.17860937, 0.28689926,
       0.2454712 , 0.43903408, 0.00942449, 0.24260207, 0.3517041 ,
       0.96164545, 0.34360194, 0.80925399, 0.29380715, 0.05083106,
       0.18185026, 0.08672094, 0.42230881, 0.18738272, 0.03011609,
       0.03949127, 0.24741115, 0.42783534, 0.10529495, 0.3797045 ,
       0.99355915, 0.10666515, 0.39100854, 0.76882483, 0.36866404,
       0.45776045, 0.95035414, 0.41991241, 0.39155199, 0.04376026,
       0.3729412 , 0.90128847, 0.88176787, 0.88842897, 0.33084181,
       0.06930658, 0.95264769, 0.20056477, 0.26055514, 0.35464233,
       0.10359064, 0.08168647, 0.4504351 , 0.09221174, 0.08648

In [16]:
from sklearn.metrics import roc_curve

fpr, tpr, thresholds = roc_curve(y_test, y_scores)

In [17]:
fpr

array([0.        , 0.        , 0.        , 0.00917431, 0.00917431,
       0.02752294, 0.02752294, 0.0733945 , 0.0733945 , 0.08256881,
       0.08256881, 0.09174312, 0.09174312, 0.10091743, 0.10091743,
       0.11009174, 0.11009174, 0.12844037, 0.12844037, 0.14678899,
       0.14678899, 0.1559633 , 0.1559633 , 0.17431193, 0.17431193,
       0.18348624, 0.18348624, 0.22018349, 0.22018349, 0.30275229,
       0.30275229, 0.35779817, 0.35779817, 0.39449541, 0.39449541,
       0.40366972, 0.40366972, 0.42201835, 0.42201835, 0.53211009,
       0.53211009, 0.5412844 , 0.5412844 , 0.57798165, 0.57798165,
       0.63302752, 0.63302752, 0.66055046, 0.66055046, 0.74311927,
       0.74311927, 0.98165138, 0.98165138, 1.        ])

In [18]:
thresholds

array([       inf, 0.99355915, 0.95264769, 0.95246057, 0.82470318,
       0.76882483, 0.76199143, 0.68386609, 0.67530864, 0.67422219,
       0.65117837, 0.65084842, 0.63548857, 0.58629992, 0.57563916,
       0.56974263, 0.52516059, 0.47017832, 0.46130908, 0.4504351 ,
       0.43903408, 0.43865787, 0.42230881, 0.41991241, 0.413039  ,
       0.41198118, 0.40477725, 0.3797045 , 0.36866404, 0.31020275,
       0.30880412, 0.27772454, 0.27204918, 0.2551059 , 0.25508365,
       0.24741115, 0.2454712 , 0.23664635, 0.22887413, 0.18185026,
       0.17860937, 0.17458294, 0.17326248, 0.14638126, 0.14075491,
       0.11671443, 0.11494283, 0.11000726, 0.10666515, 0.08923267,
       0.08672094, 0.02001692, 0.0193144 , 0.00160784])

In [21]:
import plotly.graph_objects as go
import numpy as np


# Generate a trace for ROC curve
trace0 = go.Scatter(
    x=fpr,
    y=tpr,
    mode='lines',
    name='ROC curve'
)

# Only label every nth point to avoid cluttering
n = 10
indices = np.arange(len(thresholds)) % n == 0  # Choose indices where index mod n is 0

trace1 = go.Scatter(
    x=fpr[indices],
    y=tpr[indices],
    mode='markers+text',
    name='Threshold points',
    text=[f"Thr={thr:.2f}" for thr in thresholds[indices]],
    textposition='top center'
)


# Diagonal line
trace2 = go.Scatter(
    x=[0, 1],
    y=[0, 1],
    mode='lines',
    name='Random (Area = 0.5)',
    line=dict(dash='dash')
)

data = [trace0, trace1, trace2]

# Define layout with square aspect ratio
layout = go.Layout(
    title='Receiver Operating Characteristic',
    xaxis=dict(title='False Positive Rate'),
    yaxis=dict(title='True Positive Rate'),
    autosize=False,
    width=800,
    height=800,
    showlegend=False
)

# Define figure and add data
fig = go.Figure(data=data, layout=layout)

# Show figure
fig.show()

In [22]:
# Assume that fpr, tpr, thresholds have already been calculated
optimal_idx = np.argmax(tpr - fpr)
optimal_threshold = thresholds[optimal_idx]
print("Optimal threshold is:", optimal_threshold)

Optimal threshold is: 0.36866404061737074
